import pprint
from variables_and_constants import initial_population
from functions import calculate_decimal_array_from_binary_data


initial_array = initial_population
pprint.pprint(calculate_decimal_array_from_binary_data(initial_array))
